# Generated by Django 3.1.1 on 2020-09-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200917_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_color',
            field=models.CharField(choices=[('red', 'Red'), ('blu', 'Blue'), ('gre', 'Green')], default='unknown', max_length=3),
        ),
    ]
