# Generated by Django 3.1.1 on 2020-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200918_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
