# Generated by Django 3.1.1 on 2020-09-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
    ]
